INSERT INTO MHTEAM.DWDQ.INF_B_SUB_DASH_KPI_COUNTS_5_2

SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME,
ORG,
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
CDE_CLM_TYPE,
CDE_CLM_DISPOSITION,
DOS_RECS_3MON,
DOS_RECS_3MON_12_MNTH_RLNG_AV,
CASE
    WHEN DOS_RECS_3MON_12_MNTH_RLNG_AV = 0 THEN 0
    ELSE DOS_RECS_3MON / DOS_RECS_3MON_12_MNTH_RLNG_AV 
END AS DOS_RECS_3MON_PCT,
DOS_PAID_3MON,
DOS_PAID_3MON_12_MNTH_RLNG_AV,
CASE
    WHEN DOS_PAID_3MON_12_MNTH_RLNG_AV = 0 THEN 0
    ELSE DOS_PAID_3MON / DOS_PAID_3MON_12_MNTH_RLNG_AV 
END AS DOS_PAID_3MON_PCT 
FROM (

-- rolling WH MON average 12 months over 3 MON DOS
SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME,
ORG,
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
CDE_CLM_TYPE,
CDE_CLM_DISPOSITION,
DOS_RECS_3MON,

    AVG(DOS_RECS_3MON)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION 
        ORDER BY WH_MON
        ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS DOS_RECS_3MON_12_MNTH_RLNG_AV,

DOS_PAID_3MON,
    AVG(DOS_PAID_3MON)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION
        ORDER BY WH_MON
        ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS DOS_PAID_3MON_12_MNTH_RLNG_AV
FROM (

-- now at WH MON - push 3 month sum onto prev months
SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME,
ORG,
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
CDE_CLM_TYPE,
CDE_CLM_DISPOSITION,
MAX(TOTAL_RECS_3MON) AS DOS_RECS_3MON,
MAX(TOTAL_PAID_3MON) AS DOS_PAID_3MON
        
FROM (

-- Sum for WH_MON over last 4 DOS (4 because none in WH_MON = DOS_MON except maybe at end of month?)
SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME,
ORG,
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
DOS_MON,
CDE_CLM_TYPE,
CDE_CLM_DISPOSITION,
TOTAL_RECS,

    SUM(TOTAL_RECS)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, WH_MON
        ORDER BY DOS_MON
        ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_3MON,

TOTAL_PAID,

    SUM(TOTAL_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, WH_MON
        ORDER BY DOS_MON
        ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_3MON

        
FROM (
-- counts and sum for DOS
SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME,
ORG,
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
DOS_MON,
CDE_CLM_TYPE,
CDE_CLM_DISPOSITION,
COUNT(ENC_CLAIM_NO||ENC_CLAIM_SUFFIX) AS TOTAL_RECS,
SUM(AMT_PAID) AS TOTAL_PAID,
FROM (
-- core
SELECT
CURRENT_DATE() AS RUN_DATE,
                 cw.CDE_ENTITY_MODEL, 
                 cw.ENTITY_PIDSL,
                 cw.ENTITY_NAME,
                 cw.ORG,
                 cw.MCO_CURRENT AS CLAIM_MCE,
                 CASE WHEN cw.ACO_CURRENT in('#','+','-') 
                     THEN cw.MCO_CURRENT ELSE cw.ACO_CURRENT END AS CLAIM_ACO_MCE,
                 ENC_CLAIM_NO,
                 ENC_CLAIM_SUFFIX,
                 TO_CHAR(DOS_FROM_DT,'YYMM') AS DOS_MON,
                 TO_CHAR(WH_FROM_DT,'YYMM') AS WH_MON,
                 AMT_PAID,
                 CDE_CLM_TYPE,
                 CDE_CLM_DISPOSITION
                 FROM mhdwprod.nw.nw_encounter_hist e
         left join mhteam.dwdq.INF_B_MCE_PIDSL_CROSSWALK cw on cw.mco = e.cde_enc_mco and cw.aco = e.cde_enc_aco            
         WHERE e.dos_from_dt >= '01-JAN-2022'
         AND e.IND_OFFSET = 'N'
         --AND e.CDE_ENC_ACO != 'LAHEY'
)
GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME,
         ORG,
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON, 
         DOS_MON,
         CDE_CLM_TYPE,
         CDE_CLM_DISPOSITION         

ORDER BY RUN_DATE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CLAIM_MCE, CLAIM_ACO_MCE, WH_MON, DOS_MON

)
GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME,
         ORG,
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON, 
         DOS_MON,
         CDE_CLM_TYPE,
         CDE_CLM_DISPOSITION,
         TOTAL_RECS,
         TOTAL_PAID
HAVING DOS_MON >= TO_CHAR(DATEADD(month, -4, TO_DATE(WH_MON,'YYMM')),'YYMM')

)

GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME,
         ORG,
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON,
         CDE_CLM_TYPE,
         CDE_CLM_DISPOSITION

-- Sum for WH_MON over last 4 DOS (4 because none in WH_MON = DOS_MON except maybe at end of month?)
)
GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME,
         ORG,
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON,
         CDE_CLM_TYPE,
         CDE_CLM_DISPOSITION,         
         DOS_RECS_3MON,
         DOS_PAID_3MON

-- percent
)
ORDER BY RUN_DATE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CLAIM_MCE, CLAIM_ACO_MCE, WH_MON DESC
;
