-----------------------
-- April 1 - 5.1 thru 5.3

-- 5.2

SELECT * FROM INF_B_SUB_DASH_KPI_COUNTS
limit 10;

--DROP VIEW INF_B_SUB_DASH_KPI_COUNTS
/*
-- Creates nulls

--CREATE VIEW WH_COUNTS
CREATE VIEW INF_B_SUB_DASH_KPI_COUNTS
AS 
SELECT tw.*, th.EIGHT_MON_RECS, th.EIGHT_MON_PAID 
FROM INF_B_SUB_DASH_KPI_COUNTS_5_2 tw
FULL JOIN INF_B_SUB_DASH_KPI_COUNTS_5_3 th
ON  tw.RUN_DATE            = th.RUN_DATE
AND tw.ENTITY_PIDSL        = th.ENTITY_PIDSL
AND tw.WH_MON              = th.WH_MON
AND tw.CDE_CLM_TYPE        = th.CDE_CLM_TYPE
AND tw.CDE_CLM_DISPOSITION = th.CDE_CLM_DISPOSITION
ORDER BY tw.ENTITY_PIDSL, tw.WH_MON DESC;
*/

CREATE VIEW INF_B_SUB_DASH_KPI_COUNTS
AS 
SELECT
    nvl(tw.RUN_DATE,th.RUN_DATE) RUN_DATE,
	nvl(tw.CDE_ENTITY_MODEL,th.CDE_ENTITY_MODEL) CDE_ENTITY_MODEL,
	nvl(tw.ENTITY_PIDSL,th.ENTITY_PIDSL) ENTITY_PIDSL,
	nvl(tw.ENTITY_NAME,th.ENTITY_NAME) ENTITY_NAME,
	nvl(tw.CLAIM_MCE,th.CLAIM_MCE) CLAIM_MCE,
	nvl(tw.CLAIM_ACO_MCE,th.CLAIM_ACO_MCE) CLAIM_ACO_MCE,
	nvl(tw.WH_MON,th.WH_MON) WH_MON,
	nvl(tw.CDE_CLM_TYPE,th.CDE_CLM_TYPE) CDE_CLM_TYPE,
	nvl(tw.CDE_CLM_DISPOSITION,th.CDE_CLM_DISPOSITION) CDE_CLM_DISPOSITION,
	nvl(tw.DOS_RECS_3MON,0) DOS_RECS_3MON,
	nvl(tw.DOS_RECS_3MON_12_MNTH_RLNG_AV,0.01) DOS_RECS_3MON_12_MNTH_RLNG_AV,
	nvl(tw.DOS_RECS_3MON_PCT,0) DOS_RECS_3MON_PCT,
	nvl(tw.DOS_PAID_3MON,0) DOS_PAID_3MON,
	nvl(tw.DOS_PAID_3MON_12_MNTH_RLNG_AV,0.01) DOS_PAID_3MON_12_MNTH_RLNG_AV,
	nvl(tw.DOS_PAID_3MON_PCT,0) DOS_PAID_3MON_PCT,
	nvl(th.EIGHT_MON_RECS,0) EIGHT_MON_RECS,
	nvl(th.EIGHT_MON_PAID,0) EIGHT_MON_PAID
FROM INF_B_SUB_DASH_KPI_COUNTS_5_2 tw
FULL JOIN INF_B_SUB_DASH_KPI_COUNTS_5_3 th
ON  tw.RUN_DATE            = th.RUN_DATE
AND tw.ENTITY_PIDSL        = th.ENTITY_PIDSL
AND tw.WH_MON              = th.WH_MON
AND tw.CDE_CLM_TYPE        = th.CDE_CLM_TYPE
AND tw.CDE_CLM_DISPOSITION = th.CDE_CLM_DISPOSITION
WHERE tw.CDE_ENTITY_MODEL IS NOT NULL OR th.CDE_ENTITY_MODEL IS NOT NULL  -- LAHEY
ORDER BY tw.ENTITY_PIDSL, tw.WH_MON DESC;


select * from INF_B_SUB_DASH_KPI_COUNTS
where cde_entity_model is null
;


--WHERE tw.CLAIM_MCE = 'BMC'

SELECT * FROM WH_COUNTS_5_2
WHERE CLAIM_MCE = 'BMC';

SELECT * FROM WH_COUNTS_5_3
WHERE CLAIM_MCE = 'BMC';

------------
-- 5/7/2025
-- Add Disposition AND Claim Type

TRUNCATE TABLE MHTEAM.DWDQ.INF_B_SUB_DASH_KPI_COUNTS_5_2;

SELECT *
FROM INF_B_SUB_DASH_KPI_COUNTS_5_2;


--DROP TABLE INF_B_SUB_DASH_KPI_COUNTS_5_2;

--CREATE TABLE INF_B_SUB_DASH_KPI_COUNTS_5_2
--AS

INSERT INTO MHTEAM.DWDQ.INF_B_SUB_DASH_KPI_COUNTS_5_2

SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
CDE_CLM_TYPE,
CDE_CLM_DISPOSITION,
DOS_RECS_3MON,
DOS_RECS_3MON_12_MNTH_RLNG_AV,
CASE
    WHEN DOS_RECS_3MON_12_MNTH_RLNG_AV = 0 THEN 0
    ELSE DOS_RECS_3MON / DOS_RECS_3MON_12_MNTH_RLNG_AV 
END AS DOS_RECS_3MON_PCT,
DOS_PAID_3MON,
DOS_PAID_3MON_12_MNTH_RLNG_AV,
CASE
    WHEN DOS_PAID_3MON_12_MNTH_RLNG_AV = 0 THEN 0
    ELSE DOS_PAID_3MON / DOS_PAID_3MON_12_MNTH_RLNG_AV 
END AS DOS_PAID_3MON_PCT 
FROM (

-- rolling WH MON average 12 months over 3 MON DOS
SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
CDE_CLM_TYPE,
CDE_CLM_DISPOSITION,
DOS_RECS_3MON,

    AVG(DOS_RECS_3MON)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE 
        ORDER BY WH_MON
        ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS DOS_RECS_3MON_12_MNTH_RLNG_AV,

DOS_PAID_3MON,
    AVG(DOS_PAID_3MON)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE
        ORDER BY WH_MON
        ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS DOS_PAID_3MON_12_MNTH_RLNG_AV
FROM (

-- now at WH MON - push 3 month sum onto prev months
SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
CDE_CLM_TYPE,
CDE_CLM_DISPOSITION,
MAX(TOTAL_RECS_3MON) AS DOS_RECS_3MON,
MAX(TOTAL_PAID_3MON) AS DOS_PAID_3MON
        
FROM (

-- Sum for WH_MON over last 4 DOS (4 because none in WH_MON = DOS_MON except maybe at end of month?)
SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
DOS_MON,
CDE_CLM_TYPE,
CDE_CLM_DISPOSITION,
TOTAL_RECS,

    SUM(TOTAL_RECS)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON
        ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_3MON,

TOTAL_PAID,

    SUM(TOTAL_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON
        ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_3MON

        
FROM (
-- counts and sum for DOS
SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
DOS_MON,
CDE_CLM_TYPE,
CDE_CLM_DISPOSITION,
COUNT(ENC_CLAIM_NO||ENC_CLAIM_SUFFIX) AS TOTAL_RECS,
SUM(AMT_PAID) AS TOTAL_PAID,
FROM (
-- core
SELECT
CURRENT_DATE() AS RUN_DATE,
                 cw.CDE_ENTITY_MODEL, 
                 cw.ENTITY_PIDSL,
                 cw.ENTITY_NAME,
                 cw.MCO_CURRENT AS CLAIM_MCE,
                 CASE WHEN cw.ACO_CURRENT in('#','+','-') 
                     THEN cw.MCO_CURRENT ELSE cw.ACO_CURRENT END AS CLAIM_ACO_MCE,
                 ENC_CLAIM_NO,
                 ENC_CLAIM_SUFFIX,
                 TO_CHAR(DOS_FROM_DT,'YYMM') AS DOS_MON,
                 TO_CHAR(WH_FROM_DT,'YYMM') AS WH_MON,
                 AMT_PAID,
                 CDE_CLM_TYPE,
                 CDE_CLM_DISPOSITION
                 FROM mhdwprod.nw.nw_encounter_hist e
         left join mhteam.dwdq.INF_B_MCE_PIDSL_CROSSWALK cw on cw.mco = e.cde_enc_mco and cw.aco = e.cde_enc_aco            
         WHERE e.dos_from_dt >= '01-JAN-2022'
         AND e.IND_OFFSET = 'N'
         AND e.CDE_ENC_ACO != 'LAHEY'
)
GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON, 
         DOS_MON,
         CDE_CLM_TYPE,
         CDE_CLM_DISPOSITION         

ORDER BY RUN_DATE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CLAIM_MCE, CLAIM_ACO_MCE, WH_MON, DOS_MON

)
GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON, 
         DOS_MON,
         CDE_CLM_TYPE,
         CDE_CLM_DISPOSITION,
         TOTAL_RECS,
         TOTAL_PAID
HAVING DOS_MON >= TO_CHAR(DATEADD(month, -4, TO_DATE(WH_MON,'YYMM')),'YYMM')

)

GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON,
         CDE_CLM_TYPE,
         CDE_CLM_DISPOSITION

-- Sum for WH_MON over last 4 DOS (4 because none in WH_MON = DOS_MON except maybe at end of month?)
)
GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON,
         CDE_CLM_TYPE,
         CDE_CLM_DISPOSITION,         
         DOS_RECS_3MON,
         DOS_PAID_3MON

-- percent
)
ORDER BY RUN_DATE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CLAIM_MCE, CLAIM_ACO_MCE, WH_MON DESC
;
