-----------------------
-- April 1 - 5.1 thru 5.3

--------------
-- add in 3 month windows - with WH_MON min fields


select WH_MON, DOS_MON, TOTAL_RECS, TOTAL_RECS_3MON, TOTAL_RECS_6_MNTH_RLNG_AV, TOTAL_RECS_6_MNTH_RLNG_AV_3MON
from DOS_ACO_RLNG_6_3MON
order by 
WH_MON DESC, 
DOS_MON DESC
;

--DROP TABLE DOS_ACO_RLNG_6;

CREATE TABLE DOS_ACO_RLNG_6_3MON
AS
SELECT 
RUN_DATE,

CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
DOS_MON,

TOTAL_RECS,
TOTAL_PAID,

    AVG(TOTAL_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_6_MNTH_RLNG_AV,
    AVG(TOTAL_RECS)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_6_MNTH_RLNG_AV,

TOTAL_RECS_3MON,
TOTAL_PAID_3MON,
        
    AVG(TOTAL_PAID_3MON)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_6_MNTH_RLNG_AV_3MON,
    AVG(TOTAL_RECS_3MON)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_6_MNTH_RLNG_AV_3MON

FROM (

SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
DOS_MON, 
--COUNT(ENC_CLAIM_NO||ENC_CLAIM_SUFFIX) AS TOTAL_RECS,
--SUM(AMT_PAID) AS TOTAL_PAID,

    SUM(AMT_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_3MON,
        
    COUNT(ENC_CLAIM_NO||ENC_CLAIM_SUFFIX)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_3MON

FROM (

SELECT
--TO_DATE('20250225','YYYYMMDD') AS RUN_DATE,
CURRENT_DATE() AS RUN_DATE,
                 cw.CDE_ENTITY_MODEL, 
                 cw.ENTITY_PIDSL,
                 cw.ENTITY_NAME,
                 E.CDE_ENC_MCO AS CLAIM_MCE,
                 CASE WHEN E.CDE_ENC_ACO in('#','+','-') 
                     THEN E.CDE_ENC_MCO ELSE E.CDE_ENC_ACO END AS CLAIM_ACO_MCE,
                 ENC_CLAIM_NO,
                 ENC_CLAIM_SUFFIX,
                 TO_CHAR(DOS_FROM_DT,'YYMM') AS DOS_MON,
                 TO_CHAR(WH_FROM_DT,'YYMM') AS WH_MON,
                 AMT_PAID
                 FROM mhdwprod.nw.nw_encounter_hist e
         left join mhteam.dwdq.INF_B_MCE_PIDSL_CROSSWALK cw on cw.mco = e.cde_enc_mco and cw.aco = e.cde_enc_aco            
         WHERE e.dos_from_dt >= '01-JAN-2022'
         AND e.IND_OFFSET = 'N'
and E.CDE_ENC_ACO = 'BMC-BACO'
)
GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON, 
         DOS_MON--,
--AMT_PAID,
--ENC_CLAIM_NO||ENC_CLAIM_SUFFIX
         
ORDER BY RUN_DATE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CLAIM_MCE, CLAIM_ACO_MCE, WH_MON, DOS_MON

)
GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON, 
         DOS_MON, 
         TOTAL_RECS,
         TOTAL_PAID,
TOTAL_RECS_3MON,
TOTAL_PAID_3MON

ORDER BY RUN_DATE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CLAIM_MCE, CLAIM_ACO_MCE, WH_MON, DOS_MON
;

--------------
-- with WH_MON min fields

select WH_MON, DOS_MON, TOTAL_RECS, TOTAL_RECS_6_MNTH_RLNG_AV
from DOS_ACO_RLNG_6
order by 
WH_MON DESC, 
DOS_MON DESC
;

--DROP TABLE DOS_ACO_RLNG_6;

CREATE TABLE DOS_ACO_RLNG_6
AS
SELECT 
RUN_DATE,

CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
DOS_MON, 
TOTAL_RECS,
TOTAL_PAID,

    AVG(TOTAL_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_12_MNTH_RLNG_AV,
    AVG(TOTAL_RECS)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_12_MNTH_RLNG_AV,

    AVG(TOTAL_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_6_MNTH_RLNG_AV,
    AVG(TOTAL_RECS)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_6_MNTH_RLNG_AV

FROM (

SELECT 
RUN_DATE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
WH_MON, 
DOS_MON, 
COUNT(DISTINCT ENC_CLAIM_NO||ENC_CLAIM_SUFFIX) AS TOTAL_RECS,
SUM(AMT_PAID) AS TOTAL_PAID
FROM (

SELECT
--TO_DATE('20250225','YYYYMMDD') AS RUN_DATE,
CURRENT_DATE() AS RUN_DATE,
                 cw.CDE_ENTITY_MODEL, 
                 cw.ENTITY_PIDSL,
                 cw.ENTITY_NAME,
                 E.CDE_ENC_MCO AS CLAIM_MCE,
                 CASE WHEN E.CDE_ENC_ACO in('#','+','-') 
                     THEN E.CDE_ENC_MCO ELSE E.CDE_ENC_ACO END AS CLAIM_ACO_MCE,
                 ENC_CLAIM_NO,
                 ENC_CLAIM_SUFFIX,
                 TO_CHAR(DOS_FROM_DT,'YYMM') AS DOS_MON,
                 TO_CHAR(WH_FROM_DT,'YYMM') AS WH_MON,
                 AMT_PAID
                 FROM mhdwprod.nw.nw_encounter_hist e
         left join mhteam.dwdq.INF_B_MCE_PIDSL_CROSSWALK cw on cw.mco = e.cde_enc_mco and cw.aco = e.cde_enc_aco            
         WHERE e.dos_from_dt >= '01-JAN-2022'
         AND e.IND_OFFSET = 'N'
and E.CDE_ENC_ACO = 'BMC-BACO'
)
GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON, 
         DOS_MON 
ORDER BY RUN_DATE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CLAIM_MCE, CLAIM_ACO_MCE, WH_MON, DOS_MON

)
GROUP BY RUN_DATE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         WH_MON, 
         DOS_MON, 
         TOTAL_RECS,
         TOTAL_PAID
ORDER BY RUN_DATE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CLAIM_MCE, CLAIM_ACO_MCE, WH_MON, DOS_MON
;

------------------
-- with WH_MON
select * 
from DOS_ACO_RLNG_6
WHERE CLAIM_MCE = 'BMC'
AND CDE_ENTITY_MODEL = 'ACOA'
AND CDE_CLM_DISPOSITION = 'V'
order by 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
CDE_CLM_TYPE, 
DOS_MON DESC,
WH_MON DESC
;

select DOS_MON, WH_MON, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, TOTAL_RECS, TOTAL_RECS_12_MNTH_RLNG_AV, TOTAL_RECS_6_MNTH_RLNG_AV
from DOS_ACO_RLNG_6
WHERE CLAIM_MCE = 'BMC'
AND CDE_ENTITY_MODEL = 'ACOA'
AND CDE_CLM_DISPOSITION = 'V'
order by 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
CDE_CLM_TYPE, 
DOS_MON DESC
;



--DROP TABLE DOS_ACO_RLNG_6;

CREATE TABLE DOS_ACO_RLNG_6
AS
SELECT 
RUN_DATE, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CDE_CLM_TYPE, 
CDE_CLM_DISPOSITION, 
WH_MON, 
DOS_MON, 
TOTAL_RECS,
TOTAL_PAID,

    AVG(TOTAL_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_24_MNTH_RLNG_AV,
    AVG(TOTAL_RECS)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_24_MNTH_RLNG_AV,

    AVG(TOTAL_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_12_MNTH_RLNG_AV,
    AVG(TOTAL_RECS)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_12_MNTH_RLNG_AV,

    AVG(TOTAL_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_6_MNTH_RLNG_AV,
    AVG(TOTAL_RECS)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, WH_MON
        ORDER BY DOS_MON 
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_6_MNTH_RLNG_AV

FROM (

SELECT 
RUN_DATE, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CDE_CLM_TYPE, 
CDE_CLM_DISPOSITION, 
WH_MON, 
DOS_MON, 
COUNT(CDE_CLM_DISPOSITION) AS TOTAL_DISP,
COUNT(DISTINCT ENC_CLAIM_NO||ENC_CLAIM_SUFFIX) AS TOTAL_RECS,
SUM(AMT_PAID) AS TOTAL_PAID
FROM (

SELECT
--TO_DATE('20250225','YYYYMMDD') AS RUN_DATE,
CURRENT_DATE() AS RUN_DATE,
                 E.CDE_ENC_MCO AS CLAIM_MCE,
                 CASE WHEN E.CDE_ENC_ACO in('#','+','-') 
                     THEN E.CDE_ENC_MCO ELSE E.CDE_ENC_ACO END AS CLAIM_ACO_MCE,
                 cw.CDE_ENTITY_MODEL, 
                 cw.ENTITY_PIDSL,
                 cw.ENTITY_NAME,
                 CDE_CLM_TYPE,
                 CDE_CLM_DISPOSITION,
                 ENC_CLAIM_NO,
                 ENC_CLAIM_SUFFIX,
                 TO_CHAR(DOS_FROM_DT,'YYMM') AS DOS_MON,
                 TO_CHAR(WH_FROM_DT,'YYMM') AS WH_MON,
                 AMT_PAID
                 FROM mhdwprod.nw.nw_encounter_hist e
         left join mhteam.dwdq.INF_B_MCE_PIDSL_CROSSWALK cw on cw.mco = e.cde_enc_mco and cw.aco = e.cde_enc_aco            
         WHERE e.dos_from_dt >= '01-JAN-2022'
         AND e.IND_OFFSET = 'N'
and E.CDE_ENC_ACO = 'BMC-BACO'
--limit 10
)
GROUP BY RUN_DATE, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CDE_CLM_TYPE, 
         CDE_CLM_DISPOSITION,
         WH_MON, 
         DOS_MON 
ORDER BY RUN_DATE, CLAIM_MCE, CLAIM_ACO_MCE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, WH_MON, DOS_MON

)
GROUP BY RUN_DATE, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CDE_CLM_TYPE, 
         CDE_CLM_DISPOSITION,
         WH_MON, 
         DOS_MON, 
         TOTAL_RECS,
         TOTAL_PAID
ORDER BY RUN_DATE, CLAIM_MCE, CLAIM_ACO_MCE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, WH_MON, DOS_MON
--limit 100
;

-------------

-- without WH_MON
select * 
from DOS_ACO_RLNG_6
WHERE CLAIM_MCE = 'BMC'
AND CDE_ENTITY_MODEL = 'ACOA'
AND CDE_CLM_DISPOSITION = 'V'
order by 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
CDE_CLM_TYPE, 
DOS_MON DESC
;

select DOS_MON, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, TOTAL_RECS, TOTAL_RECS_12_MNTH_RLNG_AV, TOTAL_RECS_6_MNTH_RLNG_AV
from DOS_ACO_RLNG_6
WHERE CLAIM_MCE = 'BMC'
AND CDE_ENTITY_MODEL = 'ACOA'
AND CDE_CLM_DISPOSITION = 'V'
order by 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
CDE_CLM_TYPE, 
DOS_MON DESC
;


--DROP TABLE DOS_ACO_RLNG_6;

CREATE TABLE DOS_ACO_RLNG_6
AS
SELECT 
RUN_DATE, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CDE_CLM_TYPE, 
CDE_CLM_DISPOSITION, 
DOS_MON, 
TOTAL_RECS,
TOTAL_PAID,

    AVG(TOTAL_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION
        ORDER BY DOS_MON 
        ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_24_MNTH_RLNG_AV,
    AVG(TOTAL_RECS)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION
        ORDER BY DOS_MON 
        ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_24_MNTH_RLNG_AV,

    AVG(TOTAL_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION
        ORDER BY DOS_MON 
        ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_12_MNTH_RLNG_AV,
    AVG(TOTAL_RECS)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION
        ORDER BY DOS_MON 
        ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_12_MNTH_RLNG_AV,

    AVG(TOTAL_PAID)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION
        ORDER BY DOS_MON 
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TOTAL_PAID_6_MNTH_RLNG_AV,
    AVG(TOTAL_RECS)
        OVER (
        PARTITION BY CLAIM_MCE, CLAIM_ACO_MCE, CDE_CLM_TYPE, CDE_CLM_DISPOSITION
        ORDER BY DOS_MON 
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TOTAL_RECS_6_MNTH_RLNG_AV

FROM (

SELECT 
RUN_DATE, 
CLAIM_MCE, 
CLAIM_ACO_MCE, 
CDE_ENTITY_MODEL, 
ENTITY_PIDSL, 
ENTITY_NAME, 
CDE_CLM_TYPE, 
CDE_CLM_DISPOSITION,
DOS_MON, 
COUNT(CDE_CLM_DISPOSITION) AS TOTAL_DISP,
COUNT(DISTINCT ENC_CLAIM_NO||ENC_CLAIM_SUFFIX) AS TOTAL_RECS,
SUM(AMT_PAID) AS TOTAL_PAID
FROM (

SELECT
--TO_DATE('20250225','YYYYMMDD') AS RUN_DATE,
CURRENT_DATE() AS RUN_DATE,
                 E.CDE_ENC_MCO AS CLAIM_MCE,
                 CASE WHEN E.CDE_ENC_ACO in('#','+','-') 
                     THEN E.CDE_ENC_MCO ELSE E.CDE_ENC_ACO END AS CLAIM_ACO_MCE,
                 cw.CDE_ENTITY_MODEL, 
                 cw.ENTITY_PIDSL,
                 cw.ENTITY_NAME,
                 CDE_CLM_TYPE,
                 CDE_CLM_DISPOSITION,
                 ENC_CLAIM_NO,
                 ENC_CLAIM_SUFFIX,
                 TO_CHAR(DOS_FROM_DT,'YYMM') AS DOS_MON,
                 AMT_PAID
                 FROM mhdwprod.nw.nw_encounter_hist e
         left join mhteam.dwdq.INF_B_MCE_PIDSL_CROSSWALK cw on cw.mco = e.cde_enc_mco and cw.aco = e.cde_enc_aco            
         WHERE e.dos_from_dt >= '01-JAN-2022'
         AND e.IND_OFFSET = 'N'
and E.CDE_ENC_ACO = 'BMC-BACO'
--limit 10
)
GROUP BY RUN_DATE, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CDE_CLM_TYPE, 
         CDE_CLM_DISPOSITION,
         DOS_MON 
ORDER BY RUN_DATE, CLAIM_MCE, CLAIM_ACO_MCE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, DOS_MON

)
GROUP BY RUN_DATE, 
         CLAIM_MCE, 
         CLAIM_ACO_MCE, 
         CDE_ENTITY_MODEL, 
         ENTITY_PIDSL, 
         ENTITY_NAME, 
         CDE_CLM_TYPE, 
         CDE_CLM_DISPOSITION,
         DOS_MON, 
         TOTAL_RECS,
         TOTAL_PAID
ORDER BY RUN_DATE, CLAIM_MCE, CLAIM_ACO_MCE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, CDE_CLM_TYPE, CDE_CLM_DISPOSITION, DOS_MON
;
