create or replace TABLE MHTEAM.DWDQ.INF_B_MCE_PIDSL_CROSSWALK (
	MCE_GROUP VARCHAR(10),
	MCE_NUM NUMBER(38,0),
	CDE_ENTITY_MODEL VARCHAR(5),
	MCO VARCHAR(5),
	MCO_CURRENT VARCHAR(5),
	ACO VARCHAR(20),
	ACO_CURRENT VARCHAR(20),
	ENTITY_PIDSL VARCHAR(20),
	ENTITY_NAME VARCHAR(100),
	ORG VARCHAR(100)
);

create or replace TABLE MHTEAM.DWDQ.INF_B_SQL_ERROR (
	SQLERROR VARCHAR(255)
);

create or replace TABLE MHTEAM.DWDQ.INF_B_SUB_DASH_FILE_DOS_COUNTS (
	RUN_DATE DATE,
	MCO VARCHAR(10),
	ACO VARCHAR(10),
	CDE_ENTITY_MODEL VARCHAR(10),
	ENTITY_PIDSL VARCHAR(20),
	ENTITY_NAME VARCHAR(100),
	ID VARCHAR(10),
	FILE_NAME VARCHAR(100),
	METADATA_DATE_CREATED DATE,
	DATE_FILE_PROCESSED DATE,
	MANUAL_OVERRIDE VARCHAR(1),
	AMENDMENT VARCHAR(1),
	METADATA_TOTAL_RECORDS NUMBER(10,0),
	LOADED_RECORD_COUNT NUMBER(10,0),
	ERROR_RECORD_COUNT NUMBER(10,0),
	METADATA_TOTAL_PAYMENTS NUMBER(15,2),
	DOS_MON VARCHAR(4),
	RECORD_TYPE VARCHAR(1),
	RECORD_COUNT NUMBER(10,0)
);

create or replace TABLE MHTEAM.DWDQ.INF_B_SUB_DASH_KPI_COUNTS_5_2 (
	RUN_DATE DATE,
	CDE_ENTITY_MODEL VARCHAR(5),
	ENTITY_PIDSL VARCHAR(20),
	ENTITY_NAME VARCHAR(100),
	ORG VARCHAR(100),
	CLAIM_MCE VARCHAR(5),
	CLAIM_ACO_MCE VARCHAR(20),
	WH_MON VARCHAR(16777216),
	CDE_CLM_TYPE VARCHAR(1),
	CDE_CLM_DISPOSITION VARCHAR(1),
	DOS_RECS_3MON NUMBER(30,0),
	DOS_RECS_3MON_12_MNTH_RLNG_AV NUMBER(38,3),
	DOS_RECS_3MON_PCT NUMBER(38,6),
	DOS_PAID_3MON NUMBER(33,2),
	DOS_PAID_3MON_12_MNTH_RLNG_AV NUMBER(38,5),
	DOS_PAID_3MON_PCT NUMBER(38,8)
);

create or replace TABLE MHTEAM.DWDQ.INF_B_SUB_DASH_KPI_COUNTS_5_3 (
	RUN_DATE DATE,
	CDE_ENTITY_MODEL VARCHAR(5),
	ENTITY_PIDSL VARCHAR(20),
	ENTITY_NAME VARCHAR(100),
	ORG VARCHAR(100),
	CLAIM_MCE VARCHAR(5),
	CLAIM_ACO_MCE VARCHAR(20),
	WH_MON VARCHAR(16777216),
	CDE_CLM_TYPE VARCHAR(1),
	CDE_CLM_DISPOSITION VARCHAR(1),
	EIGHT_MON_RECS NUMBER(30,0),
	EIGHT_MON_PAID NUMBER(33,2)
);

create or replace TABLE MHTEAM.DWDQ.INF_B_SUB_DASH_WH_DOS_ACO_COUNTS (
	RUN_DATE DATE,
	WH_MON VARCHAR(4),
	DOS_MON VARCHAR(4),
	CLAIM_MCE VARCHAR(10),
	CLAIM_ACO_MCE VARCHAR(10),
	CDE_ENTITY_MODEL VARCHAR(10),
	ENTITY_PIDSL VARCHAR(20),
	ENTITY_NAME VARCHAR(100),
	CDE_CLM_TYPE VARCHAR(1),
	CDE_CLM_DISPOSITION VARCHAR(2),
	RECORD_COUNT NUMBER(38,0)
);







