create or replace view MHTEAM.DWDQ.INF_B_SUB_DASH_KPI_COUNTS(
	RUN_DATE,
	CDE_ENTITY_MODEL,
	ENTITY_PIDSL,
	ENTITY_NAME,
	ORG,
	CLAIM_MCE,
	CLAIM_ACO_MCE,
	WH_MON,
	CDE_CLM_TYPE,
	CDE_CLM_DISPOSITION,
	DOS_RECS_3MON,
	DOS_RECS_3MON_12_MNTH_RLNG_AV,
	DOS_RECS_3MON_PCT,
	DOS_PAID_3MON,
	DOS_PAID_3MON_12_MNTH_RLNG_AV,
	DOS_PAID_3MON_PCT,
	EIGHT_MON_RECS,
	EIGHT_MON_PAID
) as 
SELECT
    nvl(tw.RUN_DATE,th.RUN_DATE) RUN_DATE,
	nvl(tw.CDE_ENTITY_MODEL,th.CDE_ENTITY_MODEL) CDE_ENTITY_MODEL,
	nvl(tw.ENTITY_PIDSL,th.ENTITY_PIDSL) ENTITY_PIDSL,
	nvl(tw.ENTITY_NAME,th.ENTITY_NAME) ENTITY_NAME,
	nvl(tw.ORG,th.ORG) ORG,
	nvl(tw.CLAIM_MCE,th.CLAIM_MCE) CLAIM_MCE,
	nvl(tw.CLAIM_ACO_MCE,th.CLAIM_ACO_MCE) CLAIM_ACO_MCE,
	nvl(tw.WH_MON,th.WH_MON) WH_MON,
	nvl(tw.CDE_CLM_TYPE,th.CDE_CLM_TYPE) CDE_CLM_TYPE,
	nvl(tw.CDE_CLM_DISPOSITION,th.CDE_CLM_DISPOSITION) CDE_CLM_DISPOSITION,
	nvl(tw.DOS_RECS_3MON,0) DOS_RECS_3MON,
	nvl(tw.DOS_RECS_3MON_12_MNTH_RLNG_AV,0.01) DOS_RECS_3MON_12_MNTH_RLNG_AV,
	nvl(tw.DOS_RECS_3MON_PCT,0) DOS_RECS_3MON_PCT,
	nvl(tw.DOS_PAID_3MON,0) DOS_PAID_3MON,
	nvl(tw.DOS_PAID_3MON_12_MNTH_RLNG_AV,0.01) DOS_PAID_3MON_12_MNTH_RLNG_AV,
	nvl(tw.DOS_PAID_3MON_PCT,0) DOS_PAID_3MON_PCT,
	nvl(th.EIGHT_MON_RECS,0) EIGHT_MON_RECS,
	nvl(th.EIGHT_MON_PAID,0) EIGHT_MON_PAID
FROM INF_B_SUB_DASH_KPI_COUNTS_5_2 tw
FULL JOIN INF_B_SUB_DASH_KPI_COUNTS_5_3 th
ON  tw.RUN_DATE            = th.RUN_DATE
AND tw.ENTITY_PIDSL        = th.ENTITY_PIDSL
AND tw.WH_MON              = th.WH_MON
AND tw.CDE_CLM_TYPE        = th.CDE_CLM_TYPE
AND tw.CDE_CLM_DISPOSITION = th.CDE_CLM_DISPOSITION
WHERE tw.CDE_ENTITY_MODEL IS NOT NULL OR th.CDE_ENTITY_MODEL IS NOT NULL  -- LAHEY
ORDER BY tw.ENTITY_PIDSL, tw.WH_MON DESC;

create or replace view MHTEAM.DWDQ.INF_B_SUB_DASH_WH_DOS_ACO_AVG_PCT(
	RUN_DATE,
	DOS_MON,
	CLAIM_MCE,
	CLAIM_ACO_MCE,
	CDE_ENTITY_MODEL,
	ENTITY_PIDSL,
	ENTITY_NAME,
	REC_COUNT,
	AVG_RECS,
	SD_RECS,
	PCT_RECS
) as
SELECT * FROM (

SELECT t.RUN_DATE, t.DOS_MON, t.CLAIM_MCE, t.CLAIM_ACO_MCE, t.CDE_ENTITY_MODEL, t.ENTITY_PIDSL, t.ENTITY_NAME, t.REC_COUNT, a.AVG_RECS, a.SD_RECS,
t.REC_COUNT/(a.AVG_RECS) AS PCT_RECS
FROM (
SELECT RUN_DATE, DOS_MON, CLAIM_MCE, CLAIM_ACO_MCE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME,
    SUM(RECORD_COUNT) AS REC_COUNT
FROM INF_B_SUB_DASH_WH_DOS_ACO_COUNTS
GROUP BY RUN_DATE, DOS_MON, CLAIM_MCE, CLAIM_ACO_MCE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME
) AS t
INNER JOIN INF_B_SUB_DASH_WH_DOS_ACO_AVG_SD AS a ON t.RUN_DATE = a.RUN_DATE AND t.CLAIM_MCE = a.CLAIM_MCE AND t.CLAIM_ACO_MCE = a.CLAIM_ACO_MCE
--ORDER BY RUN_DATE, DOS_MON, CLAIM_MCE, CLAIM_ACO_MCE

)
--WHERE CLAIM_MCE = 'NHP'

ORDER BY RUN_DATE, DOS_MON, CLAIM_MCE, CLAIM_ACO_MCE;

create or replace view MHTEAM.DWDQ.INF_B_SUB_DASH_WH_DOS_ACO_AVG_SD(
	RUN_DATE,
	CLAIM_MCE,
	CLAIM_ACO_MCE,
	CDE_ENTITY_MODEL,
	ENTITY_PIDSL,
	ENTITY_NAME,
	AVG_RECS,
	SD_RECS
) as
SELECT RUN_DATE, CLAIM_MCE, CLAIM_ACO_MCE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, AVG(RECORD_COUNT) AVG_RECS, STDDEV (RECORD_COUNT) SD_RECS
FROM (
SELECT RUN_DATE, CLAIM_MCE, CLAIM_ACO_MCE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, DOS_MON,
    SUM(RECORD_COUNT) AS RECORD_COUNT
FROM INF_B_SUB_DASH_WH_DOS_ACO_COUNTS
GROUP BY RUN_DATE, CLAIM_MCE, CLAIM_ACO_MCE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, DOS_MON
ORDER BY RUN_DATE, CLAIM_MCE, CLAIM_ACO_MCE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME, DOS_MON
)
GROUP BY RUN_DATE, CLAIM_MCE, CLAIM_ACO_MCE, CDE_ENTITY_MODEL, ENTITY_PIDSL, ENTITY_NAME
ORDER BY RUN_DATE, CLAIM_MCE, CLAIM_ACO_MCE;

create or replace view MHTEAM.DWDQ.INF_B_SUB_DASH_WH_DOS_MCO_AVG_PCT(
	RUN_DATE,
	DOS_MON,
	CLAIM_MCE,
	CDE_ENTITY_MODEL,
	REC_COUNT,
	AVG_RECS,
	SD_RECS,
	PCT_RECS
) as
SELECT * FROM (

SELECT t.RUN_DATE, t.DOS_MON, t.CLAIM_MCE, t.CDE_ENTITY_MODEL, t.REC_COUNT, a.AVG_RECS, a.SD_RECS,
t.REC_COUNT/(a.AVG_RECS) AS PCT_RECS
FROM (
SELECT RUN_DATE, DOS_MON, CLAIM_MCE, CDE_ENTITY_MODEL,
    SUM(RECORD_COUNT) AS REC_COUNT
FROM INF_B_SUB_DASH_WH_DOS_ACO_COUNTS
GROUP BY RUN_DATE, DOS_MON, CLAIM_MCE, CDE_ENTITY_MODEL
) AS t
INNER JOIN INF_B_SUB_DASH_WH_DOS_MCO_AVG_SD AS a ON t.RUN_DATE = a.RUN_DATE AND t.CLAIM_MCE = a.CLAIM_MCE

)

ORDER BY RUN_DATE, DOS_MON, CLAIM_MCE;

create or replace view MHTEAM.DWDQ.INF_B_SUB_DASH_WH_DOS_MCO_AVG_SD(
	RUN_DATE,
	CLAIM_MCE,
	CDE_ENTITY_MODEL,
	AVG_RECS,
	SD_RECS
) as
SELECT RUN_DATE, CLAIM_MCE, CDE_ENTITY_MODEL, AVG(RECORD_COUNT) AVG_RECS, STDDEV (RECORD_COUNT) SD_RECS
FROM (
SELECT RUN_DATE, CLAIM_MCE, CDE_ENTITY_MODEL, DOS_MON,
    SUM(RECORD_COUNT) AS RECORD_COUNT
FROM INF_B_SUB_DASH_WH_DOS_ACO_COUNTS
GROUP BY RUN_DATE, CLAIM_MCE, CDE_ENTITY_MODEL, DOS_MON
ORDER BY RUN_DATE, CLAIM_MCE, CDE_ENTITY_MODEL, DOS_MON
)
GROUP BY RUN_DATE, CLAIM_MCE, CDE_ENTITY_MODEL
ORDER BY RUN_DATE, CLAIM_MCE;





